export const GET_SUMMONER = 'GET_SUMMONER';
export const SET_SUMMONER = 'SET_SUMMONER';
export const GET_CHAMPION_MASTERY = 'GET_CHAMPION_MASTERY';
export const SET_CHAMPION_MASTERY = 'SET_CHAMPION_MASTERY';
export const SET_FETCH_STATUS = 'SET_FETCH_STATUS';
